// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operations.proto

package token

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TokenOperation describes a token operation
type TokenOperation struct {
	// Types that are valid to be assigned to Operation:
	//	*TokenOperation_Action
	Operation            isTokenOperation_Operation `protobuf_oneof:"Operation"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TokenOperation) Reset()         { *m = TokenOperation{} }
func (m *TokenOperation) String() string { return proto.CompactTextString(m) }
func (*TokenOperation) ProtoMessage()    {}
func (*TokenOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b4a5877375e491e, []int{0}
}

func (m *TokenOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenOperation.Unmarshal(m, b)
}
func (m *TokenOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenOperation.Marshal(b, m, deterministic)
}
func (m *TokenOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenOperation.Merge(m, src)
}
func (m *TokenOperation) XXX_Size() int {
	return xxx_messageInfo_TokenOperation.Size(m)
}
func (m *TokenOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenOperation.DiscardUnknown(m)
}

var xxx_messageInfo_TokenOperation proto.InternalMessageInfo

type isTokenOperation_Operation interface {
	isTokenOperation_Operation()
}

type TokenOperation_Action struct {
	Action *TokenOperationAction `protobuf:"bytes,1,opt,name=Action,proto3,oneof"`
}

func (*TokenOperation_Action) isTokenOperation_Operation() {}

func (m *TokenOperation) GetOperation() isTokenOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *TokenOperation) GetAction() *TokenOperationAction {
	if x, ok := m.GetOperation().(*TokenOperation_Action); ok {
		return x.Action
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TokenOperation) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TokenOperation_Action)(nil),
	}
}

// TokenOperationAction lists the available operations
type TokenOperationAction struct {
	// Types that are valid to be assigned to Payload:
	//	*TokenOperationAction_Issue
	//	*TokenOperationAction_Transfer
	Payload              isTokenOperationAction_Payload `protobuf_oneof:"Payload"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *TokenOperationAction) Reset()         { *m = TokenOperationAction{} }
func (m *TokenOperationAction) String() string { return proto.CompactTextString(m) }
func (*TokenOperationAction) ProtoMessage()    {}
func (*TokenOperationAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b4a5877375e491e, []int{1}
}

func (m *TokenOperationAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenOperationAction.Unmarshal(m, b)
}
func (m *TokenOperationAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenOperationAction.Marshal(b, m, deterministic)
}
func (m *TokenOperationAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenOperationAction.Merge(m, src)
}
func (m *TokenOperationAction) XXX_Size() int {
	return xxx_messageInfo_TokenOperationAction.Size(m)
}
func (m *TokenOperationAction) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenOperationAction.DiscardUnknown(m)
}

var xxx_messageInfo_TokenOperationAction proto.InternalMessageInfo

type isTokenOperationAction_Payload interface {
	isTokenOperationAction_Payload()
}

type TokenOperationAction_Issue struct {
	Issue *TokenActionTerms `protobuf:"bytes,1,opt,name=Issue,proto3,oneof"`
}

type TokenOperationAction_Transfer struct {
	Transfer *TokenActionTerms `protobuf:"bytes,2,opt,name=Transfer,proto3,oneof"`
}

func (*TokenOperationAction_Issue) isTokenOperationAction_Payload() {}

func (*TokenOperationAction_Transfer) isTokenOperationAction_Payload() {}

func (m *TokenOperationAction) GetPayload() isTokenOperationAction_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *TokenOperationAction) GetIssue() *TokenActionTerms {
	if x, ok := m.GetPayload().(*TokenOperationAction_Issue); ok {
		return x.Issue
	}
	return nil
}

func (m *TokenOperationAction) GetTransfer() *TokenActionTerms {
	if x, ok := m.GetPayload().(*TokenOperationAction_Transfer); ok {
		return x.Transfer
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TokenOperationAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TokenOperationAction_Issue)(nil),
		(*TokenOperationAction_Transfer)(nil),
	}
}

// TokenActionTerms describes the expected sender and outputs of a token operation
type TokenActionTerms struct {
	// Sender is the party who should perform the operation
	Sender *TokenOwner `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	// Outputs contains the expected outputs
	Outputs              []*Token `protobuf:"bytes,2,rep,name=Outputs,proto3" json:"Outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenActionTerms) Reset()         { *m = TokenActionTerms{} }
func (m *TokenActionTerms) String() string { return proto.CompactTextString(m) }
func (*TokenActionTerms) ProtoMessage()    {}
func (*TokenActionTerms) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b4a5877375e491e, []int{2}
}

func (m *TokenActionTerms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenActionTerms.Unmarshal(m, b)
}
func (m *TokenActionTerms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenActionTerms.Marshal(b, m, deterministic)
}
func (m *TokenActionTerms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenActionTerms.Merge(m, src)
}
func (m *TokenActionTerms) XXX_Size() int {
	return xxx_messageInfo_TokenActionTerms.Size(m)
}
func (m *TokenActionTerms) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenActionTerms.DiscardUnknown(m)
}

var xxx_messageInfo_TokenActionTerms proto.InternalMessageInfo

func (m *TokenActionTerms) GetSender() *TokenOwner {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *TokenActionTerms) GetOutputs() []*Token {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func init() {
	proto.RegisterType((*TokenOperation)(nil), "token.TokenOperation")
	proto.RegisterType((*TokenOperationAction)(nil), "token.TokenOperationAction")
	proto.RegisterType((*TokenActionTerms)(nil), "token.TokenActionTerms")
}

func init() { proto.RegisterFile("operations.proto", fileDescriptor_1b4a5877375e491e) }

var fileDescriptor_1b4a5877375e491e = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd0, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0xe0, 0xa6, 0xd2, 0xd4, 0x4e, 0x44, 0xda, 0x45, 0x30, 0xe8, 0xa5, 0x44, 0x90, 0xea,
	0x61, 0x03, 0x95, 0x3e, 0x80, 0x39, 0xd5, 0x53, 0x35, 0xe6, 0xe4, 0x6d, 0x93, 0x4c, 0xd3, 0x60,
	0x9b, 0x0d, 0xb3, 0x1b, 0xa4, 0x8f, 0xe0, 0x5b, 0x4b, 0xb2, 0x69, 0x49, 0x45, 0xf0, 0xb8, 0xfc,
	0xdf, 0x3f, 0xcc, 0x0e, 0x8c, 0x65, 0x89, 0x24, 0x74, 0x2e, 0x0b, 0xc5, 0x4b, 0x92, 0x5a, 0xb2,
	0x81, 0x96, 0x9f, 0x58, 0xdc, 0x4c, 0x34, 0x89, 0x42, 0x89, 0xa4, 0x8e, 0x4c, 0xe2, 0x45, 0x70,
	0x19, 0xd5, 0xd9, 0xea, 0x50, 0x61, 0x0b, 0xb0, 0x9f, 0x1b, 0xe1, 0x5a, 0x53, 0x6b, 0xe6, 0xcc,
	0x6f, 0x79, 0x53, 0xe6, 0xa7, 0xcc, 0x90, 0x65, 0x2f, 0x6c, 0x71, 0xe0, 0xc0, 0xe8, 0x18, 0x7a,
	0xdf, 0x16, 0x5c, 0xfd, 0xe5, 0x99, 0x0f, 0x83, 0x17, 0xa5, 0x2a, 0x6c, 0x67, 0x5f, 0x77, 0x67,
	0x1b, 0x12, 0x21, 0xed, 0xd4, 0xb2, 0x17, 0x1a, 0xc7, 0x16, 0x70, 0x1e, 0xd5, 0x4b, 0xaf, 0x91,
	0xdc, 0xfe, 0x7f, 0x9d, 0x23, 0x0d, 0x46, 0x30, 0x7c, 0x15, 0xfb, 0xad, 0x14, 0xa9, 0x87, 0x30,
	0xfe, 0x4d, 0xd9, 0x03, 0xd8, 0xef, 0x58, 0xa4, 0x48, 0xed, 0x1e, 0x93, 0x93, 0x3f, 0x7e, 0x15,
	0x48, 0x61, 0x0b, 0xd8, 0x3d, 0x0c, 0x57, 0x95, 0x2e, 0x2b, 0xad, 0xdc, 0xfe, 0xf4, 0x6c, 0xe6,
	0xcc, 0x2f, 0xba, 0x36, 0x3c, 0x84, 0xc1, 0x1b, 0xdc, 0x49, 0xca, 0xf8, 0x66, 0x5f, 0x22, 0x6d,
	0x31, 0xcd, 0x90, 0xf8, 0x5a, 0xc4, 0x94, 0x27, 0xe6, 0xd0, 0xca, 0xb4, 0x3e, 0x1e, 0xb3, 0x5c,
	0x6f, 0xaa, 0x98, 0x27, 0x72, 0xe7, 0x77, 0xac, 0x6f, 0xac, 0x6f, 0xac, 0xdf, 0xd8, 0xd8, 0x6e,
	0x5e, 0x4f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xea, 0x79, 0x8f, 0xd0, 0x01, 0x00, 0x00,
}
