// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package token

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResourcePublic struct {
	ResourceID           string   `protobuf:"bytes,1,opt,name=ResourceID,proto3" json:"ResourceID,omitempty"`
	OrganizationID       string   `protobuf:"bytes,2,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	ResourceHash         []byte   `protobuf:"bytes,3,opt,name=ResourceHash,proto3" json:"ResourceHash,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,4,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourcePublic) Reset()         { *m = ResourcePublic{} }
func (m *ResourcePublic) String() string { return proto.CompactTextString(m) }
func (*ResourcePublic) ProtoMessage()    {}
func (*ResourcePublic) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *ResourcePublic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcePublic.Unmarshal(m, b)
}
func (m *ResourcePublic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcePublic.Marshal(b, m, deterministic)
}
func (m *ResourcePublic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcePublic.Merge(m, src)
}
func (m *ResourcePublic) XXX_Size() int {
	return xxx_messageInfo_ResourcePublic.Size(m)
}
func (m *ResourcePublic) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcePublic.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcePublic proto.InternalMessageInfo

func (m *ResourcePublic) GetResourceID() string {
	if m != nil {
		return m.ResourceID
	}
	return ""
}

func (m *ResourcePublic) GetOrganizationID() string {
	if m != nil {
		return m.OrganizationID
	}
	return ""
}

func (m *ResourcePublic) GetResourceHash() []byte {
	if m != nil {
		return m.ResourceHash
	}
	return nil
}

func (m *ResourcePublic) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*ResourcePublic)(nil), "token.ResourcePublic")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0x4f,
	0xcb, 0xcc, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xc9, 0xcf, 0x4e, 0xcd,
	0x53, 0x9a, 0xc5, 0xc8, 0xc5, 0x17, 0x94, 0x5a, 0x9c, 0x5f, 0x5a, 0x94, 0x9c, 0x1a, 0x50, 0x9a,
	0x94, 0x93, 0x99, 0x2c, 0x24, 0xc7, 0xc5, 0x05, 0x13, 0xf1, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x42, 0x12, 0x11, 0x52, 0xe3, 0xe2, 0xf3, 0x2f, 0x4a, 0x4f, 0xcc, 0xcb, 0xac, 0x4a,
	0x2c, 0xc9, 0xcc, 0xcf, 0xf3, 0x74, 0x91, 0x60, 0x02, 0xab, 0x41, 0x13, 0x15, 0x52, 0xe2, 0xe2,
	0x81, 0xe9, 0xf2, 0x48, 0x2c, 0xce, 0x90, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x09, 0x42, 0x11, 0x13,
	0x92, 0xe1, 0xe2, 0x84, 0xd8, 0xea, 0x9d, 0x5a, 0x29, 0xc1, 0x02, 0x56, 0x80, 0x10, 0x48, 0x62,
	0x03, 0x3b, 0xd5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x80, 0x8c, 0xb8, 0xbb, 0x00, 0x00,
	0x00,
}
