// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token/profile.proto

package token

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Profile public info
type ProfilePublic struct {
	ProfileId string `protobuf:"bytes,1,opt,name=profileId,proto3" json:"profileId,omitempty"`
	//organization to whom the profile is associated with
	Organization         string   `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfilePublic) Reset()         { *m = ProfilePublic{} }
func (m *ProfilePublic) String() string { return proto.CompactTextString(m) }
func (*ProfilePublic) ProtoMessage()    {}
func (*ProfilePublic) Descriptor() ([]byte, []int) {
	return fileDescriptor_20159ef9a8adf415, []int{0}
}

func (m *ProfilePublic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilePublic.Unmarshal(m, b)
}
func (m *ProfilePublic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilePublic.Marshal(b, m, deterministic)
}
func (m *ProfilePublic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilePublic.Merge(m, src)
}
func (m *ProfilePublic) XXX_Size() int {
	return xxx_messageInfo_ProfilePublic.Size(m)
}
func (m *ProfilePublic) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilePublic.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilePublic proto.InternalMessageInfo

func (m *ProfilePublic) GetProfileId() string {
	if m != nil {
		return m.ProfileId
	}
	return ""
}

func (m *ProfilePublic) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func init() {
	proto.RegisterType((*ProfilePublic)(nil), "token.ProfilePublic")
}

func init() { proto.RegisterFile("token/profile.proto", fileDescriptor_20159ef9a8adf415) }

var fileDescriptor_20159ef9a8adf415 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xc9, 0xcf, 0x4e,
	0xcd, 0xd3, 0x2f, 0x28, 0xca, 0x4f, 0xcb, 0xcc, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x05, 0x0b, 0x2a, 0x05, 0x72, 0xf1, 0x06, 0x40, 0xc4, 0x03, 0x4a, 0x93, 0x72, 0x32, 0x93,
	0x85, 0x64, 0xb8, 0x38, 0xa1, 0x0a, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10,
	0x02, 0x42, 0x4a, 0x5c, 0x3c, 0xf9, 0x45, 0xe9, 0x89, 0x79, 0x99, 0x55, 0x89, 0x25, 0x99, 0xf9,
	0x79, 0x12, 0x4c, 0x60, 0x05, 0x28, 0x62, 0x49, 0x6c, 0x60, 0x0b, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x62, 0xb5, 0xcd, 0xa0, 0x77, 0x00, 0x00, 0x00,
}
